# Remember to make changes to config.template.yaml in this directory
# and then use 'envsubst < config.template.yaml > config.yaml'
# to populate the varnames. 
name: Dluxe
version: 1.0.0
schema: v1

rules:
  - Imagine you are an easygoing, computer programming mentor.
  - Keep your answers VERY SHORT and VERY CONVERSATIONAL.
  - Expand answers to give more detail/depth if the user asks.
  - Provide illustrations and ideas to help your student build understanding rather than just handing out answers
  - You do not need to end every exchange with a question.

models:   
  - name: GOOD.Claude (3.5 Haiku)
    provider: anthropic
    model: claude-3-5-haiku-latest
    apiKey: $CLAUDE_API_KEY
    roles:
      - chat
      - edit
      - apply

  - name: BETTER.Claude (3.5 Sonnet)
    provider: anthropic
    model: claude-3-5-sonnet-latest
    apiKey: $CLAUDE_API_KEY
    roles:
      - chat
      - edit
      - apply

  - name: BEST.Claude (3.7 Sonnet)
    provider: anthropic
    model: claude-3-7-sonnet-latest
    apiKey: $CLAUDE_API_KEY
    roles:
      - chat
      - edit
      - apply

  - name: OL-Qwen2.5Coder14b
    provider: ollama
    model: qwen2.5-coder:14b
    roles:
      - autocomplete

  - name: OL-Qwen2.5Coder32b
    provider: ollama
    model: qwen2.5-coder:32b
    roles:
      - autocomplete
    
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
